# List of conda and pip packages that are should be install when developing the packages
# To create the full conda environment: conda env create -f environment.yml
name: io_utils
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - netCDF4
  - matplotlib
  - cartopy>=0.18
  - cftime>=1.1.2
  - gdal<=2.4.3
  - geopandas
  - pip
  - pip:
    - pytesmo
    - pygeogrids
    - datetime
    - pyyaml
    - xarray
    - configparser
    - more_itertools
    - Equi7Grid
    - pytileproj
    - cadati
    - country-bounding-boxes
    - git+https://github.com/TUW-GEO/smecv-grid.git@master
    - git+https://github.com/TUW-GEO/veranda.git@master
    - git+https://github.com/TUW-GEO/geopathfinder.git@master
    - git+https://github.com/TUW-GEO/yeoda.git@master
    - git+https://git.geo.tuwien.ac.at/rs/developments/pygenio.git@v1.1.13#egg=pygenio