# This workflow will install Python dependencies and run tests on
# windows and linux systems with a variety of Python versions

# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Automated Tests

on:
  push:
  pull_request:
#  schedule:
#    - cron: '0 0 * * *' # daily

jobs:
  build:
    name: Build py${{ matrix.python-version }} @ ${{ matrix.os }} 🐍
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.9']
        os: ["ubuntu-latest"]
        env: ["default.yml"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environments/${{ matrix.env }}
          activate-environment: ismn
          auto-activate-base: false
      - name: Print environment infos
        shell: bash -l {0}
        run: |
          conda info -a
          conda list
          pip list
          which pip
          which python
      - name: Export Environment
        shell: bash -l {0}
        run: |
          mkdir -p .artifacts
          filename=env_py${{ matrix.python-version }}_${{ matrix.os }}.yml
          conda env export --no-builds | grep -v "prefix" > .artifacts/$filename
      - name: Install package and test
        shell: bash -l {0}
        run: |
          pip install .
          pytest -m "not geo_test_data"
      - name: Upload Coverage
        shell: bash -l {0}
        run: |
          pip install coveralls && coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
#      - name: Create wheel and dist package
#        shell: bash -l {0}
#        run: |
#          pip install setuptools_scm
#          if [ ${{ matrix.os }} == "windows-latest" ]
#          then
#            # build whls on windows
#            pip install wheel
#            python setup.py bdist_wheel --dist-dir .artifacts/dist
#          else
#            # build dist on linux
#            python setup.py sdist --dist-dir .artifacts/dist
#          fi
#          ls .artifacts/dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: .artifacts/*
  coveralls:
    name: Submit Coveralls 👚
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls && coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
